<?php
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: public, max-age=300');
$page = trim((string)($_GET['page'] ?? 'home'));
$allowed = ['home', 'privacy', 'terms', 'support'];
if (!in_array($page, $allowed, true)) {
    http_response_code(404);
    $page = 'home';
}
$titles = [
    'home' => 'BajiStyle WC Manager for ChatGPT',
    'privacy' => 'Privacy Policy — BajiStyle WC Manager',
    'terms' => 'Terms — BajiStyle WC Manager',
    'support' => 'Support — BajiStyle WC Manager',
];
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= htmlspecialchars($titles[$page], ENT_QUOTES, 'UTF-8') ?></title>
<style>body{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;background:#f7f8fa;color:#111827}.wrap{max-width:860px;margin:auto;padding:52px 20px}.hero,.card{background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:30px;margin-bottom:18px}.eyebrow{font-size:.85rem;font-weight:750;color:#475467;text-transform:uppercase;letter-spacing:.08em}h1{font-size:clamp(2rem,5vw,3.4rem);line-height:1.08;margin:.35em 0}h2{margin-top:1.4em}p,li{line-height:1.75;color:#344054}.links{display:flex;gap:14px;flex-wrap:wrap;margin-top:24px}.links a,a{color:#175cd3;text-decoration:none;font-weight:650}.pill{display:inline-block;background:#ecfdf3;color:#067647;padding:6px 10px;border-radius:999px;font-weight:700;font-size:.85rem}code{background:#f2f4f7;padding:2px 6px;border-radius:6px}.prose{background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:30px}.prose h1{font-size:2rem}.nav{margin-bottom:18px}.nav a{margin-right:14px}</style></head><body><main class="wrap">
<nav class="nav"><a href="plugin.php">Home</a><a href="plugin.php?page=privacy">Privacy</a><a href="plugin.php?page=terms">Terms</a><a href="plugin.php?page=support">Support</a></nav>
<?php if ($page === 'home'): ?>
<section class="hero"><div class="eyebrow">ChatGPT Plugin · MCP</div><h1>BajiStyle WC Manager</h1><p>Connect ChatGPT to a controlled commerce-management layer for WooCommerce, WordPress media/articles, and the configured Basalam vendor account.</p><span class="pill">OAuth 2.1 + PKCE</span></section>
<section class="card"><h2>What the Plugin can do</h2><ul><li>Search, inspect, create, and update WooCommerce products.</li><li>Import a conversation image, copy it to WordPress Media, and attach it to a product.</li><li>Read, draft, and update WordPress articles.</li><li>Read, update, and synchronize catalog data with the configured Basalam vendor.</li></ul></section>
<section class="card"><h2>Security model</h2><p>Plugin authorization is limited to active WC Manager administrators. ChatGPT receives scoped OAuth access tokens, not WooCommerce consumer secrets, WordPress application passwords, or Basalam credentials. Write actions are exposed as explicit MCP tools and are marked separately from read-only tools.</p></section>
<section class="card"><h2>Connection endpoint</h2><p>The MCP endpoint is <code>https://manage.bajistyle.ir/mcp.php</code>. Interactive authorization is handled by WC Manager over HTTPS.</p></section>
<?php elseif ($page === 'privacy'): ?>
<article class="prose"><h1>Privacy Policy</h1><p><strong>Effective date:</strong> September 6, 2026</p><p>This policy describes data processing by the BajiStyle WC Manager ChatGPT Plugin hosted at <strong>manage.bajistyle.ir</strong>.</p>
<h2>Data we process</h2><ul><li><strong>WC Manager account data:</strong> administrator username and session information used to authorize the connection. Passwords are verified by WC Manager and are not sent to ChatGPT.</li><li><strong>Commerce data:</strong> WooCommerce product IDs, names, descriptions, prices, inventory, categories, attributes, and images requested through Plugin tools.</li><li><strong>Content data:</strong> WordPress article titles, content, status, categories, and media requested through Plugin tools.</li><li><strong>Image data:</strong> images supplied by the user through a ChatGPT conversation, a public URL, or supported image payload for an explicit upload action.</li><li><strong>Basalam data:</strong> product/catalog data for the vendor account configured by the WC Manager administrator.</li><li><strong>Operational metadata:</strong> tool/action name, target identifiers, time, and OAuth client/token record identifiers used for security and troubleshooting. Raw access tokens, passwords, API secrets, and full ChatGPT prompts are not stored in Plugin audit logs.</li></ul>
<h2>Purposes</h2><p>Data is processed only to authenticate the user, perform the requested store/content operation, return the requested result, prevent abuse, troubleshoot failures, and maintain an auditable record of Plugin actions.</p>
<h2>Credentials and secrets</h2><p>WooCommerce consumer secrets, WordPress application passwords, Basalam access credentials, and WC Manager server configuration remain on the WC Manager server. They are not returned to ChatGPT by Plugin tools.</p>
<h2>Recipients and third-party services</h2><p>When the user requests an action, relevant data may be transmitted to the connected WooCommerce/WordPress site and, for Basalam operations, to Basalam. ChatGPT acts as the MCP client initiating the user's requested operation. We do not sell Plugin data or use it for advertising or cross-service profiling.</p>
<h2>Retention</h2><ul><li>OAuth authorization codes: up to 5 minutes and deleted after use/expiry.</li><li>OAuth access tokens: up to 1 hour.</li><li>OAuth refresh tokens: up to 30 days unless revoked earlier.</li><li>Plugin-specific MCP/OAuth audit logs: up to 90 days.</li><li>Images imported into WC Manager or WordPress Media remain until a store administrator deletes them.</li><li>Product, article, and Basalam content remains according to the retention/deletion controls of those connected systems.</li></ul>
<h2>User controls</h2><p>Users can disconnect the Plugin from ChatGPT. OAuth tokens can be revoked and expire automatically. Store administrators can edit or delete media/content in the connected systems. For assistance with access or deletion requests, use the Support page.</p>
<h2>Security</h2><p>The Plugin uses HTTPS, OAuth authorization code flow with PKCE S256, scoped permissions, short-lived access tokens, one-way token hashes at rest, administrator-only authorization, login throttling, and action logging.</p><h2>Changes</h2><p>Material changes to this policy will be published on this page with a new effective date.</p></article>
<?php elseif ($page === 'terms'): ?>
<article class="prose"><h1>Terms of Service</h1><p><strong>Effective date:</strong> September 6, 2026</p><h2>Authorized use</h2><p>The Plugin is intended for users authorized to manage the connected WC Manager, WooCommerce/WordPress site, and Basalam vendor account. Only active WC Manager administrators may authorize a ChatGPT connection.</p><h2>Actions and responsibility</h2><p>Some Plugin tools create or modify products, media, articles, prices, inventory, or marketplace data. The user is responsible for reviewing requested changes before approving or instructing publication or synchronization. Write tools are classified separately from read-only tools so the client can apply appropriate confirmation controls.</p><h2>Third-party services</h2><p>WooCommerce, WordPress, Basalam, and OpenAI/ChatGPT are separate services with their own terms and availability. This Plugin does not grant rights beyond the user's existing permissions in those systems.</p><h2>Security</h2><p>Users must protect their WC Manager account and must not share credentials or access tokens. Access may be restricted or revoked where abuse, unauthorized use, or a security risk is detected.</p><h2>Availability</h2><p>The Plugin is provided on an as-available basis. External API changes, network failures, rate limits, marketplace moderation, or connected-site configuration can affect individual actions.</p><h2>Intellectual property</h2><p>Users retain responsibility for content and images they direct the Plugin to upload or publish and must have the necessary rights to use that material.</p><h2>OpenAI relationship</h2><p>BajiStyle WC Manager is an independent integration and is not an OpenAI product. ChatGPT is used as an MCP client when the user chooses to connect the Plugin.</p></article>
<?php else: ?>
<article class="prose"><h1>Support</h1><p>For Plugin connection, authorization, WooCommerce, WordPress media/article, or Basalam integration issues, open a support issue in the WC Manager GitHub repository.</p><p><a href="https://github.com/ebrahimsadati1377-star/wc-manager/issues" rel="noopener noreferrer">Open a WC Manager support issue</a></p><h2>Include in a support report</h2><ul><li>The Plugin tool name that failed.</li><li>Approximate time of the request.</li><li>The returned error message or status code.</li><li>Do not include passwords, OAuth tokens, WooCommerce secrets, WordPress application passwords, or Basalam access tokens.</li></ul></article>
<?php endif; ?></main></body></html>
